components:
  schemas:
    Item:
      properties:
        name:
          type: string
        price:
          format: float
          type: number
        quantity:
          type: integer
      required:
      - name
      - price
      - quantity
      type: object
info:
  title: Item API
  version: 1.0.0
openapi: 3.0.3
paths:
  /items:
    get:
      responses:
        '200':
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/Item'
                type: array
          description: A list of items
      summary: Retrieve all items
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Item'
        required: true
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Item'
          description: Item created successfully
        '400':
          description: Invalid input
      summary: Create a new item
  /items/{itemId}:
    get:
      parameters:
      - in: path
        name: itemId
        required: true
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Item'
          description: The requested item
        '404':
          description: Item not found
      summary: Retrieve an item by ID
    put:
      parameters:
      - in: path
        name: itemId
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Item'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Item'
          description: Item updated successfully
        '400':
          description: Invalid input
        '404':
          description: Item not found
      summary: Update an item by ID
