# AUTOGENERATED! DO NOT EDIT! File to edit: ../../../nbs/90_utils.ipynb.

# %% auto 0
__all__ = ['res', 'check_res', 'cleanup']

# %% ../../../nbs/90_utils.ipynb 1
import os
import shutil
import glob
from pathlib import Path
from PIL import Image

# %% ../../../nbs/90_utils.ipynb 10
def res(fname):
    """return the resolution in a tuple"""
    with Image.open(fname) as img:
        w, h = img.size
        return w, h

def check_res(fname, reso):
    """check if its resolution is equal to 'reso'"""
    if reso != res(fname):
        return False
    return True

# %% ../../../nbs/90_utils.ipynb 14
def cleanup(files, resolution):
    """Remove files which are not equal to the specified resolution"""
    for f in files:
        if Path(f).exists() == False:
            print(f'{f} doesn\'t exists')
            continue
        if check_res(f, resolution) == False:
            print(f, res(f))
            os.remove(f)
